name: RetypeInstallAction 
on:
  push:
defaults:
  run:
    shell: pwsh

jobs:
  Run-Tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: Retype
      - name: 🧪 Run PowerShell tests
        run: Invoke-Pester ./tests/Retype.ps1 -Output Detailed -PassThru -ErrorAction Stop
